AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Drummon CORS Proxy
Globals:
  Function:
    Timeout: 30

Resources:
  DrummonApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
        openapi: 3.0
        paths:
          "/{proxy+}":
            get:
              x-amazon-apigateway-any-method:
                name: proxy
                in: path
                required: true
                schema:
                  type: string
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DrummonFunction.Arn}/invocations
              x-amazon-apigateway-integration:
                httpMethod: GET
                passthroughBehavior: when_no_match
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DrummonFunction.Arn}/invocations
              x-amazon-apigateway-binary-media-types:
                - "*/*"

  DrummonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.mozilla.mixedreality.Drummon::handleRequest
      Runtime: java8
      CodeUri: target/drummon-1.0-lambda-package.zip
      MemorySize: 256
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Environment:
        Variables:
          ProxyHost: http://127.0.1.1
          AllowedOrigins: https://hubs.mozilla.com
      Events:
        Proxy:
          Type: Api
          Properties:
            Path: /
            Method: get
            ContentHandling: CONVERT_TO_BINARY
